services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Skeleton2214!
      POSTGRES_DB: spotify_data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airflow_network

  airflow-webserver:
    image: apache/airflow:2.5.0
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:Skeleton2214!@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
    ports:
      - "8080:8080"
    networks:
      - airflow_network
    depends_on:
      - postgres

  airflow-scheduler:
    image: apache/airflow:2.5.0
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:Skeleton2214!@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    networks:
      - airflow_network
    depends_on:
      - postgres

  airflow-worker:
    image: apache/airflow:2.5.0
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:Skeleton2214!@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    networks:
      - airflow_network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  airflow_network:
    driver: bridge
